<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
| -------------------------------------------------------------------
| IONIZE LANGUAGES
| -------------------------------------------------------------------
| Contains the available languages definitions for the front-end.
| Auto-generated by Ionizes Language administration.
| Changes made in this file will be overwritten by languages save in Ionize.
|
|
*/

// Default admin language code
$config['default_admin_lang'] = 'en';

// Default language code
// This code depends on the language defined through the Ionize admin panel
// and will never change during the request process 
$config['default_lang_code'] = 'en_US';

// Default Translation Language Code
$config['default_translation_lang_code'] = 'en';

// Used language code
// Dynamically changed by the Router depending on the browser, cookie or asked URL
// By default, Ionize set it to the default lang code.
$config['detected_lang_code'] = 'en';

// Available languages
// Languages set through Ionize. Includes offline languages
$config['available_languages'] = array(
	'de_DE' => 'German',
	'en_US' => 'English',
	'fr_FR' => 'French',
	'hu_HU' => 'Hungarian',
	'it_IT' => 'Italian',
	'pl_PL' => 'Polish',
    'pt_BR' => 'Portuguese',
	'ru_RU' => 'Russian',
	'zh_CN' => 'Chinese'
);

// Online languages
// Languages set online through Ionize.
$config['online_languages'] = array(
	'en' => 'English'
);



/* End of file language.php */
/* Auto generated by Language Administration on : 2012.08.23 13:02:39 */
/* Location: ./application/config/language.php */
